PROGRAM FACTORIAL_TAIL_CALL;

FUNCTION FACTITER(PRODUCT, N);
BEGIN
    If N = 0 THEN FACTITER := PRODUCT
    ELSE FACTITER := FACTITER(PRODUCT * N, N - 1)
END;

FUNCTION FACTORIAL(N);
BEGIN
    FACTORIAL := FACTITER(1, N)
END;

BEGIN
    WRITELN(FACTORIAL(7))
END.
